### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by gety9** [palmettostatearmory/psa_dyblocks#1]
Hi,

I was checking your extension, copied all files into app directory

and now it gives error:

**There has been an error processing your request**

```
Error in file: "/var/www/html/app/code/community/PSA/Dyblocks/sql/psa_dyblocks_setup/mysql4-upgrade-0.1.0-0.1.1.php" - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gety_oldpark.mgn_psa_dyblocks' doesn't exist

Trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '0.1.0', '0.1.1')
#2 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('0.1.0', '0.1.1')
#3 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/html/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/html/index.php(91): Mage::run('', 'store')
#8 {main}
```

Seems like problem with set-up script.

Magento ver 1.9.2.0

**Comment by timciep** [comment]
Thanks @gety9.  This is fixed now.
